[workspace]
members = [
    "spideog-bin",
    "kraken-report-parser",
    "braken-report-parser"
]

[profile.dev]
panic = "unwind"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = true
panic = "unwind"
codegen-units = 1

